services:
  - type: web
    name: gold-calculator-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
    plan: free